version: "3.8"

services:
  # ---------- FRONTEND ----------
  admin-web:
    build:
      context: ../../frontend/admin-web
      dockerfile: Dockerfile
      args:
        VITE_APP_API_URL: ${VITE_APP_API_URL:-http://localhost:3000}
        VITE_APP_GRAFANA_URL: ${VITE_APP_GRAFANA_URL:-http://localhost:3003}
    ports:
      - "3004:80"
    depends_on: [api-gateway]
    networks: [ev-network]
    profiles: [frontend, all]

networks:
  ev-network:
    driver: bridge
